# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARProject
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'FirebaseUI/Google'
pod 'FirebaseUI/Phone'
pod 'GoogleSignIn'
pod 'AFNetworking', '3.1.0', :inhibit_warnings => true 

end
